### ISSUE TITLE
Epic : Game Rental System

### ISSUE THREAD

**Issue by sakixchy** [sakixchy/drf-api-sgr#14]
This epic encompasses all functionalities for listing games, viewing game details, requesting rentals, approving/denying requests, and managing rentals.

**Tasks:**
- [ ] Game Listing
- [ ] Game Details View
- [ ] Request Game Rental
- [ ] Approve or Deny Rental Requests
- [ ] Manage Rentals
